### ISSUE TITLE
✨ Tree structure for areas

### ISSUE THREAD

**Issue by lnabergoi** [sequentech/meta#1040] opened 2024-06-03 08:37 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

The system needs to allow the creation of a tree structure for areas, with the following implications
- voters can be assigned to each level of the tree
- voter will only see the question/contest in the voting portal of the area assigned and the higher levels
- The admin can decide to which level of the area tree he wants the resulting breakdown
- Area level on tally sheet

### Tasks

# Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment] 2024-08-16 04:13
dupe of #1063

**Closed by edulix** 2024-08-16 04:13 UTC
Labels: enhancement, triage, admin-portal
