### ISSUE TITLE
🐞 Admin Portal: Tables sort functions don't work

### ISSUE THREAD

**Issue by GuyZequent** [sequentech/meta#1480] opened 2024-07-29 09:36 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Clicking the sort buttons (ascending/descending) doesn't change the data order in the table.

https://github.com/user-attachments/assets/801d2918-bdb3-4923-bf4a-ecefd1b87257

### Expected Behavior

Data will be sorted when selecting the "sort" buttons.

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment] 2024-08-15 03:21
dupe of #1480

**Closed by edulix** 2024-08-15 03:21 UTC
Labels: bug, triage
