### ISSUE TITLE
🐞 In Election with mulitiple allowed votes - Redirect URL doesn't work

### ISSUE THREAD

**Issue by GuyZequent** [sequentech/meta#1676] opened 2024-08-08 20:56 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.

### Current Behavior

Redirect URL: www.google.com

**Ballot is configured to accept multiple votes.**

**Result: Redirected to Ballot List instead of Redirect URL**

_Note: This only occurs when multiple votes are allowed, regardless if they are cast or not._

https://github.com/user-attachments/assets/1f34cd02-9e3b-45b1-937b-f335d626452e

### Expected Behavior

After casting multiple votes - voter will be redirected to the redirect url

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment] 2024-08-15 03:06
dupe of #1189

**Closed by edulix** 2024-08-15 03:06 UTC
Labels: bug, triage

**Comment by edulix** [comment] 2024-08-15 03:08
Actually, this is not a dupe. The question is, if the voter has already voted in all elections but can still continue voting, what should be the behavior I think for now, it makes sense that the redirect url is overriden by the fact that you can vote multiple times. This is because otherwise if you can vote in 2 elections, and you already did but want to override, everytime you vote you would be redirected to the redirect url instead of the ballot list.
