### ISSUE TITLE
✨ Add error checks on voting/review screen

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#172] opened 2023-08-01 18:20 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Add error checks on voting/review screen

### Tasks

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Master PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment] 2023-09-15 11:42
Duplicate of #237

**Closed by edulix** 2023-09-15 11:42 UTC
Labels: enhancement, triage
