### ISSUE TITLE
🐞 Not all translations in a voting booth are customisable.

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [sequentech/meta#439] opened 2023-12-18 22:09 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

Some of the translations in the voting booth are not customisable in the json configuration (e.g. error messages on the login screen).

### Expected Behavior

Ensure that al translations are customizable, as agreed in the #122 

### Steps To Reproduce

login to election

### Environment

- **OS**: Mac OS X Ventura
- **Web browser**: Google Chrome 112.0.5615.137 (Official Build) (arm64)
- **Sequent Platform Version**: 10.0.0

### Tasks

```[tasklist]
# Tasks
- [ ] Issue has been triaged
- [ ] Successful replication of the defect
- [ ] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

```[tasklist]
# Stable PRs
- [ ] PR 1
```

**Comment by edulix** [comment] 2024-01-18 11:31
After reviewing this with Sergiy, we agree that the problem to be solved in this ticket is that the system messages in the login screen (from the election-portal) do not support translations coming from the election JSON config.

**Comment by edulix** [comment] 2024-03-25 12:11
@sergiydmukhinepi isn't this one the same as https://github.com/sequentech/meta/issues/680 ?

**Comment by Findeton** [comment] 2024-03-26 11:55
Hi @sergiydmukhinepi  I tested some login error translations and they’re working for me, what are the errors that you’re seeing that can’t be overriden in the election config?

**Comment by sergiydmukhinepi** [comment] 2024-03-26 22:11
@Findeton This text cannot be overwritten either https://github.com/sequentech/voting-booth/blob/master/locales/en.json#L266
https://github.com/sequentech/voting-booth/blob/master/locales/en.json#L267
https://github.com/sequentech/voting-booth/blob/master/locales/en.json#L268
https://github.com/sequentech/voting-booth/blob/master/locales/en.json#L269

**Comment by sergiydmukhinepi** [comment] 2024-03-26 22:38
@Findeton Sorry, I need to check it. I'll let you know.

**Comment by sergiydmukhinepi** [comment] 2024-04-02 13:30
@Findeton seems to work. I'll keep the issue open for a while to test it properly.

**Comment by Findeton** [comment] 2024-04-12 13:31
Closing as it's not a bug.

**Closed by Findeton** 2024-04-12 13:31 UTC
Labels: bug, epi-1
