### ISSUE TITLE
fold/unfold buttons

### ISSUE THREAD

**Issue by Jojo-newb** [sequentech/meta#1379] opened 2024-07-18 10:20 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

From a user's perspective, it is intuitive that clicking the button to open a section would also close it. 

### Possible Implementation

when I click the icon of an opened section, it will be closed back 

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

### Additional context

![Screenshot_20240718_171854_Chrome](https://github.com/user-attachments/assets/e3a32e74-6823-477d-9579-f15a2bf42604)

**Comment by edulix** [comment] 2024-08-15 03:20
dupe of #1719

**Closed by edulix** 2024-08-15 03:20 UTC
Labels: enhancement, triage
