### ISSUE TITLE
✨ Tally:  replace Hasura with Postgres queries

### ISSUE THREAD

**Issue by Findeton** [sequentech/meta#1492] opened 2024-07-29 22:51 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Suggestion

Tally:  replace Hasura with Postgres queries

### Screenshots

<empty>

```[tasklist]
# Tasks
- [ ] Task 1
```

```[tasklist]
# Main PRs
- [ ] PR 1
```

**Comment by edulix** [comment] 2024-08-16 04:12
dupe of #982

**Closed by edulix** 2024-08-16 04:12 UTC
Labels: enhancement
